import type { NextPage } from "next";
import Head from "next/head";

import { Button, styled } from "@hazy/core";
import { View, PropTypes } from "react-view";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Hazy DS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>hazy Documentation</h1>
        <p>Getting Started</p>
        <code> npm install @hazy/core</code>
      </main>
    </div>
  );
};
export default Home;
